export const GET_ERRORS='GET_ERRORS';

export const THEM_DANHMUC='THEM_DANHMUC'
export const HIENTHI_DANHMUC='HIENTHI_DANHMUC'
export const XOA_DANHMUC='XOA_DANHMUC'

export const THEM_NHASX='THEM_NHASX'
export const HIENTHI_NHASX='HIENTHI_NHASX'
export const XOA_NHASX='XOA_NHASX'

export const THEM_SANPHAM='THEM_SANPHAM'
export const HIENTHI_SANPHAMS='HIENTHI_SANPHAMS'
export const HIENTHI_SANPHAM='HIENTHI_SANPHAM'
export const XOA_SANPHAM='XOA_SANPHAM'

export const SEARCH_SANPHAM='SEARCH_SANPHAM'
export const SEARCH='SEARCH'
export const SEARCH_DANHMUC='SEARCH_DANHMUC'
export const GET_CART='GET_CART'
export const ADD_TO_CART='ADD_TO_CART'
export const UPDATE_CART='UPDATE_CART'
export const DELETE_CART_ITEM='DELETE_CART_ITEM'
export const CLEAR_CART='CLEAR_CART'

export const HIENTHI_THANHTOAN='HIENTHI_THANHTOAN'

export const SET_CURRENT_USER='SET_CURRENT_USER'

export const THANHTOAN='THANHTOAN'
export const HIENTHITHANHTOAN='HIENTHITHANHTOAN'